import { Component } from "react";
import Sidebar from "@/components/sidebar";

export const metadata = {
  title: "Dashboard | Ordering System",
  description: "Generated by create next app",
};

type PropsLayout = {
  children: React.ReactNode;
};

const RootLayout = ({ children }: PropsLayout) => {
  return (
    <Sidebar title="Dashboard">
      {children}
    </Sidebar>
  );
};

export default RootLayout;